services:
    app.form.type.recipe_ingredient:
        class: AppBundle\Form\Type\RecipeIngredientType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }