index:
    path:       /
    defaults:   { _controller: "AppBundle:Default:index" }

dashboard:
    path:       /dashboard
    defaults:   { _controller: "AppBundle:Dashboard:index" }

lab:
    path:       /lab
    defaults:   { _controller: "AppBundle:Default:lab" }

app.user:
    resource: '@AppBundle/Resources/config/routing/user.yml'

app.security:
    resource: '@AppBundle/Resources/config/routing/security.yml'

app.ingredient:
    resource: '@AppBundle/Resources/config/routing/ingredient.yml'

app.recipe:
    resource: '@AppBundle/Resources/config/routing/recipe.yml'

app.shopping_list:
    resource: '@AppBundle/Resources/config/routing/shopping_list.yml'

app.friend:
    resource: '@AppBundle/Resources/config/routing/friend.yml'

app.tag:
    resource: '@AppBundle/Resources/config/routing/tag.yml'

app.debug:
    resource: '@AppBundle/Resources/config/routing/debug.yml'
    prefix: /debug

app.api:
    resource: '@AppBundle/Resources/config/routing/api.yml'
    prefix: /api